INPUT_SIZE: [224, 224]
TRAIN_DATASET: "../data/vehicles/train/"
VALID_DATASET: "../data/vehicles/valid/"
BATCH_SIZE: 64
EPOCHS: 100
VERBOSE_STEP: 1
PATIENCE: 10
MIN_DELTA: 0.001
MAX_LR: 0.001
DIV_FACTOR: 10
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
NUM_WORKERS: 8
PERSISTENT_WORKERS: True
PIN_MEMORY: True
