MEDIUM:
  RESIZE_BLOCK: [[32, 5, 2, 2], [2, 2]]
  RESIDUAL_BLOCKS:
    [
      [[32, 3, 1, True], [32, 3, 1, True]],
      [[64, 3, 1, True], [64, 3, 1, True]],
      [[128, 3, 1, True], [128, 3, 1, True]],
      [[64, 3, 1, True], [64, 3, 1, True]],
      [[96, 5, 1, True], [96, 5, 1, True]],
      [[128, 3, 1, True], [128, 3, 1, True]],
    ]
  NECK_BLOCK: [[256, 0.4], [256, 0.4]]
