SMALL:
  INPUT_SHAPE: [224, 224]
  SHRINKAGE: [[[16, 5, 2, 2], [2, 2]]]
  RESIDUALS:
    # SeResidualBlock, SeResidualBlock, MaxDepthPool2d, MaxPool2d
    [
      [[32, 3, 1, 4, True], [32, 3, 1, 4, True], [2], [2, 2]],
      [[64, 5, 2, 8, True], [64, 5, 1, 8, True], [2], [2, 2]],
    ]
  NECK: [[256, 0.5], [128, 0.25]]
MEDIUM:
  INPUT_SHAPE: [224, 224]
  SHRINKAGE: [[[32, 5, 2, 2], [2, 2]]]
  RESIDUALS:
    [
      [[64, 3, 1, 4, True], [64, 3, 1, 4, True], [2], [2, 2]],
      [[96, 5, 1, 6, True], [96, 5, 1, 6, True], [2], [2, 2]],
      [[128, 3, 1, 8, True], [128, 3, 1, 8, True], [4], [2, 2]],
    ]
  NECK: [[512, 0.5], [256, 0.25]]
LARGE:
  INPUT_SHAPE: [448, 448]
  SHRINKAGE: [[[32, 5, 2, 2], [2, 2]]]
  RESIDUALS:
    [
      [[64, 3, 1, 4, True], [64, 3, 1, 4, True], [2], [2, 2]],
      [[96, 5, 1, 6, True], [96, 5, 1, 6, True], [2], [2, 2]],
      [[128, 3, 1, 8, True], [128, 3, 1, 8, True], [2], [2, 2]],
      [[256, 5, 1, 16, True], [256, 5, 1, 16, True], [4], [2, 2]],
    ]
  NECK: [[512, 0.5], [256, 0.25]]
