ARCHITECTURE: "medium"
TRAIN_DATASET: "../data/vehicles/train/"
VALID_DATASET: "../data/vehicles/valid/"
METRIC_AVERAGE: "macro"
BATCH_SIZE: 128
EPOCHS: 10
MONITOR: "val_loss"
PATIENCE: 10
MIN_DELTA: 1.e-3
L1_WEIGHT: 2.e-6
L2_WEIGHT: 2.e-5
MAX_LR: 1.e-3
DIV_FACTOR: 10
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
CHECKPOINTS_FREQ: 1
CHECKPOINTS_DIR: "./checkpoints/"
RESUME: False
