"Acura": 0
"Alfa Romeo": 1
"Audi": 2
"BMW": 3
"Bentley": 4
"Bugatti Veyron": 5
"Cadillac Escalade": 6
"Cadillac SRX": 7
"Chevrolet Camaro": 8
"Chevrolet Corvette": 9
"Dodge": 10
"Ferrari": 11
"Ford Mustang": 12
"Hyundai": 13
"Jeep Liberty": 14
"Kia": 15
"Lamborghini": 16
"Lexus": 17
"Maserati": 18
"Mercedes": 19
"Mitsubishi Lancer": 20
"Porsche": 21
"Renault": 22
"Rolls Royce": 23
"Toyota": 24
