ARCH_TYPE: "SEResNet3"
TRAIN_DATASET: "../datasets/cars/train/"
VALID_DATASET: "../datasets/cars/valid/"
METRIC_AVERAGE: "weighted"
BATCH_SIZE: 128
EPOCHS: 100
MONITOR: "val_loss"
PATIENCE: 10
MIN_DELTA: 0.01
L1_WEIGHT: 1.e-5
L2_WEIGHT: 1.e-4
MAX_LR: 1.e-3
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
CHECKPOINTS_FREQ: 5
CHECKPOINTS_DIR: "./checkpoints/"
RESUME: False
