ARCH_TYPE: "SEResNet3"
TRAIN_DATASET: "../data/vehicles/train/"
VALID_DATASET: "../data/vehicles/valid/"
METRIC_AVERAGE: "macro"
BATCH_SIZE: 128
EPOCHS: 100
MONITOR: "val_loss"
PATIENCE: 10
MIN_DELTA: 0.01
L1_WEIGHT: 2.e-6
L2_WEIGHT: 2.e-5
MAX_LR: 4.e-4
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
CHECKPOINTS_FREQ: 5
CHECKPOINTS_DIR: "./checkpoints/"
RESUME: False
